### ISSUE TITLE
Output Types

### ISSUE THREAD

**Issue by willtebbutt** [theogf/KernelFunctions.jl#18]
At the present time, the definition of the abstract type [Kernel](https://github.com/theogf/KernelFunctions.jl/blob/460ed8685018a35bac2bceaa2401639668a41f6e/src/KernelFunctions.jl#L30) is
```julia
abstract type Kernel{T,Tr<:Transform} end
```
with the first type parameter corresponding to the output type. I originally did this for everything in Stheno, but later dropped it in all cases where the output type is uniquely determined by the input type.

For example, the [exponentiated quadratic kernel](https://github.com/willtebbutt/Stheno.jl/blob/61236affc381d5cba16fab67b9a0d93226e8995d/src/gp/kernel.jl#L76) doesn't need to know its output type because computations involving its inputs enforce a particular type. Conversely, the inputs to the [Zero kernel](https://github.com/willtebbutt/Stheno.jl/blob/61236affc381d5cba16fab67b9a0d93226e8995d/src/gp/kernel.jl#L19) don't tie down the type of its output (only its size) so I require that you specify it, with the default being `Float64`. Moreover this kernel isn't user-facing, so they shouldn't ever need to construct it.

The reason for dropping this feature is that requiring the user to specify the output type of the kernel is a bit painful in general, and doesn't produce "canonical Julia" code -- you _can_ specify output types in Julia, but it's generally best left to the compiler to determine from the input types.

If there's not a particularly strong reason to keep the output type as part of the kernel, I would be very much in favour of dropping it.

**Comment by theogf** [comment]
Is your point to drop `T` for the abstract type or for all kernels?
If it is for abstract I can see the point but in general we might need a parametrization.
For example we need to parametrize some of the parameters for `LinearKernel` or `GammaExponential`.
Also the output of the kernel (in this parametrized case), is basically depending on how `Base` process the mix of types. For example what would a `LinearKernel{Float32,Transform}` would produce on `Float64` data. And we should be careful on this when working with AD types.

**Comment by devmotion** [comment]
I was a bit confused about the type parameter `T` and assumed that it is supposed to encode the output type, even though that is not enforced in the current implementation as
https://github.com/theogf/KernelFunctions.jl/blob/278ae6e4941dd8ebc14e5095c018a248f4fa10a4/src/kernels/matern.jl#L36
shows. Here the output is the type of `d` or the result of the computation - which is type unstable for certain input types such as `Int` or `Float32` BTW.
In other places such as
https://github.com/theogf/KernelFunctions.jl/blob/278ae6e4941dd8ebc14e5095c018a248f4fa10a4/src/kernels/matern.jl#L55
or
https://github.com/theogf/KernelFunctions.jl/blob/278ae6e4941dd8ebc14e5095c018a248f4fa10a4/src/kernels/matern.jl#L74
type parameters `T` are left in the implementation, but actually indicate the type of the distance of the inputs in the first example (in the second example `T` is not even defined) and do not affect the output type (so they could both just be removed).

I agree with @willtebbutt that usually one should let the compiler figure out the output type. IMO that's typically easier for the user, the developer, and for working with AD (in particular if one uses Tracker or ForwardDiff with custom number types). So I'm very much in favour of dropping the parameter type `T` in `Kernel{T,Tr}` and most of the kernels. For some kernels it might be required or useful to define the output type and keep `T`, but I even think that a Zero kernel doesn't necessarily have to have fixed output types - in that case one could, e.g., also use `Base.promote_eltypeof(x, y)` (if `x` and `y` are the inputs) or `float(Base.promote_eltypeof(x, y))` if one would like to obtain floating point numbers consistently.

**Comment by willtebbutt** [comment]
> Is your point to drop T for the abstract type or for all kernels?

Assuming that `T` is the output type, then yes, for all kernels. I agree with @devmotion regarding output types and AD -- it's generally nicer for all involved to let the compiler figure it out.

> For example we need to parametrize some of the parameters for LinearKernel or GammaExponential.

I had been assuming that these are a different problem. I agree that if there is non output-type-related info then that should stay.

> e.g., also use Base.promote_eltypeof(x, y) (if x and y are the inputs) or float(Base.promote_eltypeof(x, y)) if one would like to obtain floating point numbers consistently.

I like this idea, but unfortunately it doesn't work in all cases. e.g. string kernels / graph kernels etc.

**Comment by willtebbutt** [comment]
For the record, I'm happy to open a PR that tackles this.

**Comment by willtebbutt** [comment]
Closed by #26
