### ISSUE TITLE
Matern constructor type stability

### ISSUE THREAD

**Issue by willtebbutt** [theogf/KernelFunctions.jl#7]
The constructors for `Matern` are currently type-unstable. That is, the precise type that you wind up with when you call `Matern(ρ, ν)` depends on the numerical value of `ν`. This is problematic from a performance perspective (type instability is bad), but can also cause issues from a functionality perspective. Specifically, if you (for some reason) were to decide to optimise `ν` via some gradient-based procedure, and choose to use AD, the gradient w.r.t. `ν` will be zero if you start the optimisation at a value that produces a `Matern32` or `Matern52` kernel. I feel that you can reasonably call this a bug.

I propose instead to always produce a `MaternKernel` if the user calls `MaternKernel`, and only produce a `Matern32` / `Matern52` if the user specifically asks for that. We ensure that the user is aware of the latter options via documentation and example code.

**Comment by theogf** [comment]
You're absolutely right! I did not think about this! I will make the necessary corrections.
